

export const PRODUCT_GROUP = [
	{ keyName: 'BUSINESS_CARD', category: 'business-card', subCategory: 'basic' },
	{ keyName: 'TRANS_BUSINESS_CARD', category: 'business-card', subCategory: 'transparency', disabled: true },
	{ keyName: 'CARD', category: 'card', subCategory: 'flat' },
	{ keyName: 'POSTER', category: 'poster', subCategory: 'defaults' },
	{ keyName: 'STICKER', category: 'sticker', subCategory: 'circle', updateEdit: true, disabled: true },
	{ keyName: 'STICKER_2ND', category: 'sticker', subCategory: 'circle' },
	{ keyName: 'FLYER', category: 'flyer', subCategory: 'defaults' },
	{ keyName: 'BROCHURE', category: 'brochure', subCategory: 'defaults' },
	{ keyName: 'MENU', category: 'menu', subCategory: 'defaults' },
	{ keyName: 'POSTCARD', category: 'post-card', subCategory: 'defaults' },
	{ keyName: 'COUPON', category: 'coupon', subCategory: 'defaults' },
	{ keyName: 'ACCESSORY', category: 'accessory', subCategory: 'envelope' },
	{ keyName: 'PLACARD_BANNER', category: 'placard-banner', subCategory: 'defaults' },
	{ keyName: 'STANDARD_BANNER', category: 'standard-banner', subCategory: 'defaults' },
	{ keyName: 'DOUBLE_SIDE_BANNER', category: 'double-side-banner', subCategory: 'defaults' },
	{ keyName: 'ROLLUP_BANNER', category: 'rollup-banner', subCategory: 'defaults' },
	{ keyName: 'MINI_BANNER', category: 'mini-banner', subCategory: 'defaults' },
	{ keyName: 'BOARD_SIGN', category: 'board-sign', subCategory: 'defaults' },
	{ keyName: 'ACRYLIC_SIGN', category: 'acrylic-sign', subCategory: 'defaults' },
	{ keyName: 'METAL_SIGN', category: 'metal-sign', subCategory: 'defaults' },
	{ keyName: 'WOODEN_FRAME_SIGN', category: 'wooden-frame-sign', subCategory: 'defaults' },
	{ keyName: 'TABLE_TOP_SIGN', category: 'table-top-sign', subCategory: 'defaults' },
	{ keyName: 'A_FRAME_SIGN', category: 'a-frame-sign', subCategory: 'defaults' },
	{ keyName: 'CAR_MAGNET', category: 'car-magnet', subCategory: 'defaults' },
	{ keyName: 'WINDOW_DECAL', category: 'window-decal', subCategory: 'defaults' },
	{ keyName: 'APPAREL_SHORT_SLEEVES', category: 'apparel', subCategory: 'short_sleeves' },
	{ keyName: 'APPAREL_PANTS', category: 'apparel', subCategory: 'pants' },
	{ keyName: 'APPAREL_M2M_HOOD_ZIPUP', category: 'apparel', subCategory: 'm2m_hood_zipup' },
	{ keyName: 'APPAREL_ECOBAG', category: 'apparel', subCategory: 'echo_bag' },
	{ keyName: 'APPAREL_LONG_SLEEVES', category: 'apparel', subCategory: 'long_sleeves' },
	{ keyName: 'APPAREL_POUCH', category: 'apparel', subCategory: 'pouch' },
  { keyName: 'APPAREL_ONEPIECE', category: 'apparel', subCategory: 'onepiece' },
  { keyName: 'ACRYLIC_KEYRING', category: 'acrylic-keyring', subCategory: 'defaults' },
  { keyName: 'PIN_BUTTON', category: 'pin-button', subCategory: 'defaults'},
  { keyName: 'MIRROR_BUTTON', category: 'mirror-button', subCategory: 'defaults' },
  { keyName: 'MAGNET_BUTTON', category: 'magnet-button', subCategory: 'defaults' },
  { keyName: 'SMART_TOK', category: 'smart-tok', subCategory: 'defaults' },
  { keyName: 'STRAIGHT_GLASS', category: 'straight-glass', subCategory: 'defaults' },
  { keyName: 'NEW_STACK_GLASS', category: 'new-stack-glass', subCategory: 'defaults' },
  { keyName: 'TRANSLUCENT_REUSABLE_CUP', category: 'translucent-reusable-cup', subCategory: 'defaults' },
  { keyName: 'REUSABLE_CUP', category: 'reusable-cup', subCategory: 'defaults' },
  { keyName: 'ECO_TUMBLER', category: 'eco-tumbler', subCategory: 'defaults' },
  { keyName: 'NOTE_PAD', category: 'note-pad', subCategory: 'defaults' },
  { keyName: 'MEMO_PAD', category: 'memo-pad', subCategory: 'defaults' },
  { keyName: 'PVC_DIARY', category: 'pvc-diary', subCategory: 'defaults' },
  { keyName: 'SOFT_DIARY', category: 'soft-diary', subCategory: 'defaults' },
  { keyName: 'HARD_DIARY', category: 'hard-diary', subCategory: 'defaults' },
  { keyName: 'STANDARD_PEN', category: 'standard-pen', subCategory: 'defaults' },
  { keyName: 'BASIC_PEN', category: 'basic-pen', subCategory: 'defaults' },
  { keyName: 'LIGHT_PEN', category: 'light-pen', subCategory: 'defaults' },
  { keyName: 'ECO_PEN', category: 'eco-pen', subCategory: 'defaults' },
  { keyName: 'FAN', category: 'fan', subCategory: 'defaults' },
  { keyName: 'TRANS_FAN', category: 'fan', subCategory: 'defaults' },
  { keyName: 'CALENDAR_DESK', category: 'calendar-desk', subCategory: 'defaults' },
  { keyName: 'ENVELOPE', category: 'envelope', subCategory: 'defaults' },
  { keyName: 'SHOPPINGBAG', category: 'shoppingbag', subCategory: 'defaults' },
  { keyName: 'COLOR_DECAL_STICKER', category: 'color-decal', subCategory: 'defaults' },
  { keyName: 'GRAPHIC_DECAL_STICKER', category: 'graphic-decal', subCategory: 'defaults' }
];


