

/** CONFIG **/

export const UPDATE_CONFIG = 'UPDATE_CONFIG';

/** UI **/

export const RESIZE_UI_VIEW = 'RESIZE_UI_VIEW';

export const RESET_UI_SCROLL = 'RESET_UI_SCROLL';

export const UPDATE_UI_SCROLL = 'UPDATE_UI_SCROLL';

export const UPDATE_UI_LOCKED_OWNER = 'UPDATE_UI_LOCKED_OWNER';

/** LAYER **/

export const UPDATE_LAYER = 'UPDATE_LAYER';

export const UPDATE_TRANSPARENT_MODE_LAYER = 'UPDATE_TRANSPARENT_MODE_LAYER';

export const UPDATE_ROUND_MODE_LAYER = 'UPDATE_ROUND_MODE_LAYER';

export const OPEN_CONTENTS_LAYER = 'OPEN_CONTENTS_LAYER';

export const CLOSE_CONTENTS_LAYER = 'CLOSE_CONTENTS_LAYER';

export const OPEN_ALERT_LAYER = 'OPEN_ALERT_LAYER';

export const CLOSE_ALERT_LAYER = 'CLOSE_ALERT_LAYER';

export const OPEN_LOADING_LAYER = 'OPEN_LOADING_LAYER';

export const CLOSE_LOADING_LAYER = 'CLOSE_LOADING_LAYER';

export const CLOSE_LAYER = 'CLOSE_LAYER';

/** CS **/

export const APPEAR_CS = 'APPEAR_CS';

export const OPEN_CS = 'OPEN_CS';

export const CLOSE_CS = 'CLOSE_CS';

export const TOUCH_CS = 'TOUCH_CS';

export const CHANGE_CS_TITLE_BACK = 'CHANGE_CS_TITLE_BACK';

export const CHANGE_CS_TITLE_POP = 'CHANGE_CS_TITLE_POP';

export const CHANGE_CS_TAB_WIDTH = 'CHANGE_CS_TAB_WIDTH';

export const CHANGE_CS_TAB_FOCUS = 'CHANGE_CS_TAB_FOCUS';

export const CHANGE_CS_CONTENT_HEIGHT = 'CHANGE_CS_CONTENT_HEIGHT';

export const RESET_CS_CONTENT_HEIGHT = 'RESET_CS_CONTENT_HEIGHT';

export const UPDATE_CS_TALK_CONNECT = 'UPDATE_CS_TALK_CONNECT';

export const UPDATE_CS_POP_ITEM = 'UPDATE_CS_POP_ITEM';

export const TOUCH_CS_POP_ITEM = 'TOUCH_CS_POP_ITEM';

export const DRAG_CS_POP_ITEM = 'DRAG_CS_POP_ITEM';

export const SET_CS_TOP_SCROLL_SHOW = 'SET_CS_TOP_SCROLL_SHOW';

export const DELETE_CS_QNA_POP_ITEMS = 'DELETE_CS_QNA_POP_ITEMS';

/** QNA **/

export const UPDATE_QNA_LAST_ITEM = 'UPDATE_QNA_LAST_ITEM';

/** USER **/

export const FETCH_USER = 'FETCH_USER';

export const SUCCESS_USER = 'SUCCESS_USER';

export const FAILURE_USER = 'FAILURE_USER';

export const UPDATE_USER_LOGGED_IN = 'UPDATE_USER_LOGGED_IN';

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

export const RESET_USER_INFO = 'RESET_USER_INFO';

export const RESET_USER_ERROR = 'RESET_USER_ERROR';

export const CHANGE_USER_ERROR = 'CHANGE_USER_ERROR';

/** CART **/

export const RESET_CART = 'RESET_CART';

export const UPDATE_CART = 'UPDATE_CART';

export const UPDATE_CART_COUNT = 'UPDATE_CART_COUNT';

export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';

export const SEARCH_CART = 'SEARCH_CART';

/** ORDER **/

export const UPDATE_ORDER_CODE = 'UPDATE_ORDER_CODE';

export const UPDATE_ORDER_PRODUCTS = 'UPDATE_ORDER_PRODUCTS';

export const UPDATE_ORDER_PRODUCTS_BY_COUPON = 'UPDATE_ORDER_PRODUCTS_BY_COUPON';

export const UPDATE_ORDER_USER = 'UPDATE_ORDER_USER';

export const UPDATE_ORDER_COUPONS = 'UPDATE_ORDER_COUPONS';

export const UPDATE_ORDER_EXTRA_COUPONS = 'UPDATE_ORDER_EXTRA_COUPONS';

export const UPDATE_ORDER_DELIVERY_COUPONS = 'UPDATE_ORDER_DELIVERY_COUPONS';

export const UPDATE_ORDER_LOWEST_DISCOUNT_COUPONS = 'UPDATE_ORDER_LOWEST_DISCOUNT_COUPONS';

export const UPDATE_ORDER_USE_LOWEST = 'UPDATE_ORDER_USE_LOWEST';

export const UPDATE_ORDER_PAYMENT_OPTION = 'UPDATE_ORDER_PAYMENT_OPTION';

/** EDITOR **/

export const UPDATE_EDITOR_PARAMS = 'UPDATE_EDITOR_PARAMS';

export const RESET_EDITOR_PARAMS = 'RESET_EDITOR_PARAMS';

export const UPDATE_GA_PARAMS = 'UPDATE_GA_PARAMS';

// /** BBS **/

// export const UPDATE_DESIGN_QNA_PRODUCT_GROUP_CODE = 'UPDATE_DESIGN_QNA_PRODUCT_GROUP_CODE';

/** PRODUCT **/

export const UPDATE_PRODUCT_GROUP = 'UPDATE_PRODUCT_GROUP';

/** LOG **/

export const UPDATE_LOG_USED_HISTORY = 'UPDATE_LOG_USED_HISTORY';

export const UPDATE_LOG_USED_CONVERSION = 'UPDATE_LOG_USED_CONVERSION';

/** ALARM **/

export const UPDATE_ALARM_COUNT = 'UPDATE_ALARM_COUNT';

export const UPDATE_QNA_COUNT = 'UPDATE_QNA_COUNT';

export const RESET_ALL_COUNT = 'RESET_ALL_COUNT';

/** EVENT **/
export const SAVE_EVENT = 'SAVE_EVENT';
export const SAVE_ZERO_DEAL = 'SAVE_ZERO_DEAL';
