export const LOGIN = "LOGIN";

export const JOIN = "JOIN";

export const PASSWORD = "PASSWORD";

export const NOTICE = "NOTICE";

export const WELCOME = "WELCOME";

export const ALERT = "ALERT";

export const PREVIEW_PRODUCT = "PREVIEW_PRODUCT";

export const REVIEW_CREATE = "REVIEW_CREATE";

export const REVIEW_NOTIFICATION = "REVIEW_NOTIFICATION";

export const ZIPCODE = "ZIPCODE";

export const COUPON = "COUPON";

export const COLLABORATION_FUNDING = "COLLABORATION_FUNDING";

export const DELIVERY_COUPON = "DELIVERY_COUPON";

export const DELIVERY_TRACKING = "DELIVERY_TRACKING";

export const PURCHASE_AGREEMENT = "PURCHASE_AGREEMENT";

export const PAYMENT = "PAYMENT";

export const PAYMENT_INFORMATION = "PAYMENT_INFORMATION";

export const PAYMENT_CHANGE = "PAYMENT_CHANGE";

export const OFFSET_NOTICE = "OFFSET_NOTICE";

export const SHIPPING_GUIDE = "SHIPPING_GUIDE";

export const OFFSET_PRINT_GUIDE = "OFFSET_PRINT_GUIDE";

export const CJ_DELIVERY = "CJ_DELIVERY";

export const MARKETING_AGREE = "MARKETING_AGREE";

export const DEPOSIT_INFORMATION = "DEPOSIT_INFORMATION";

export const EVENTS_FUNDING = "EVENTS_FUNDING";

export const RECEIPT_PRINT = "RECEIPT_PRINT";

export const DOCUMENT_DOWNLOAD = "DOCUMENT_DOWNLOAD";

export const TAX_IN_VOICE = "TAX_IN_VOICE";

export const CASH_RECEIPT = "CASH_RECEIPT";

export const DESIGN_QNA = "DESIGN_QNA";

export const SAMPLE_PACK = "SAMPLE_PACK";

export const FAIR_APPAREL_SIZE_ALERT = "FAIR_APPAREL_SIZE_ALERT";

export const POLICY_NOTIFICATION = "POLICY_NOTIFICATION";

export const POLICY_PRIVATE = "POLICY_PRIVATE";

export const PROJECT_SAVE_AS = "PROJECT_SAVE_AS";

export const TEMPLATE_DETAIL = "TEMPLATE_DETAIL";

export const TEMPLATE_CONFIRM = "TEMPLATE_CONFIRM";

export const EVENTS_IMAGE = "EVENTS_IMAGE";

export const EVENTS_RECOMMEND = "EVENTS_RECOMMEND";

export const EVENTS_FAN_RECOMMEND = "EVENTS_FAN_RECOMMEND";

export const EVENTS_WINNER = "EVENTS_WINNER";

export const EVENTS_APPLY = "EVENTS_APPLY";

export const EVENTS_APPLY_BEFOREHAND = "EVENTS_APPLY_BEFOREHAND";

export const EVENTS_POST_COMMENT = "EVENTS_POST_COMMENT";

export const PROJECT_EDIT = "PROJECT_EDIT";

export const SMS = "SMS";

export const CART_INFORMATION = "CART_INFORMATION";

export const PRODUCT_DETAIL = "PRODUT_DETAIL";

export const DESIGN_METHOD_DELECT = "DESIGN_METHOD_DELECT";

export const CUSTOM_PERSONALIZATION_MODAL = "CUSTOM_PERSONALIZATION_MODAL";

export const COUPON_PAYMENT_SCHEDULE = "COUPON_PAYMENT_SCHEDULE";

export const ADVANCE_RESERVATION = "ADVANCE_RESERVATION";

export const DESIGN_COMPETITION = "DESIGN_COMPETITION";

export const EVENTS_BYE_2020 = "EVENTS_BYE_2020";

export const ERASER = "ERASER";

export const COMMON_GUIDE_LAYER = "COMMON_GUIDE_LAYER";

export const EVENTS_CHEER_UP_LAYER = "EVENTS_CHEER_UP_LAYER";

export const EVENTS_NEW_YEAR_PLAN_LAYER = "EVENTS_NEW_YEAR_PLAN_LAYER";
export const EVENTS_NEW_YEAR_PLAN_SUCCESS = "EVENTS_NEW_YEAR_PLAN_SUCCESS";

export const EVENTS_APP_REVIEW = "EVENTS_APP_REVIEW";

export const SMALL_BUSINESS_DAY = "SMALL_BUSINESS_DAY";

export const NEW_YEAR_WISHES = "NEW_YEAR_WISHES";

export const HOPE_MARKET = "HOPE_MARKET";

export const CS_WRITE = "CS_WRITE";

export const EVENTS_CONFIRM_BEFOREHAND = "EVENTS_CONFIRM_BEFOREHAND";

export const EVENTS_FORM = "EVENTS_FORM";

export const CART_DIGITALPLUS = "CART_DIGITALPLUS";
