export const CHAMPION_T425 = {
	attentions: ["면100%", "릴렉스핏"],
	services: [
		"CHAMPION_TITLE",
		"CHAMPION_T425_DESCRIPTION",
		"CHAMPION_T425_GALLERY",
		"CHAMPION_T425_DETAIL",
		"CHAMPION_T425_COLOR",
		"CHAMPION_T425_INFORMATION",
		"CHAMPION_T425_SIZE_INFORMATION",
		"LAUNDRY_CARE",
		"CHAMPION_T425_PRODUCT_INFORMATION",
    "PRINT_TITLE",
    "PRINT_DIGITAL_PLUS",
    "PRINT_DIGITAL_PLUS_DESCRIPTION_01",
    "PRINT_DIGITAL_PLUS_DESCRIPTION_02",
    "PRINT_DIGITAL_PLUS_DESCRIPTION_02_01",
    "PRINT_DIGITAL_PLUS_DESCRIPTION_03",
    "PRINT_DIGITAL_PLUS_DESCRIPTION_03_01",
    "PRINT_DIGITAL_PLUS_DESCRIPTION_04",
    "PRINT_DIGITAL_PLUS_DESCRIPTION_04_01",
    "PRINT_DIGITAL_PLUS_DESCRIPTION_05",
    "PRINT_DIGITAL_PLUS_DESCRIPTION_06",
    "NEW_PRINT_NALYEOM",
    "CAUTION_BACKGROUND",
    "DIGITAL_PLUS_CAUTION_BACKGROUND",
    "NEW_CAUTION_PRINT",
    "NEW_CUSTOM_DESIGN",
    "NEW_SHORT_SLEEVES_PRINT_LOCATION",
	],
	title: "챔피온 릴렉스핏 라운드 반팔<br/>(남여공용)"
};

export default {
	CHAMPION_T425
};
