export const COMFORT_COLORS_1717 = {
  attentions: ["면100%", "릴렉스핏"],
  services: [
    "COMFORT_TITLE",
    "COMFORT_COLORS_1717_DESCRIPTION",
    "COMFORT_COLORS_1717_GALLERY",
    "COMFORT_COLORS_1717_DETAIL_1",
    "COMFORT_COLORS_1717_DETAIL_2",
    "COMFORT_COLORS_1717_COLOR",
    "COMFORT_COLORS_1717_INFORMATION",
    "COMFORT_COLORS_1717_SIZE_INFORMATION",
    "LAUNDRY_CARE",
    "COMFORT_COLORS_1717_PRODUCT_INFORMATION",
    "PRINT_TITLE",
    "PRINT_DIGITAL_PLUS",
    "PRINT_DIGITAL_PLUS_DESCRIPTION_01",
    "PRINT_DIGITAL_PLUS_DESCRIPTION_02",
    "PRINT_DIGITAL_PLUS_DESCRIPTION_02_01",
    "PRINT_DIGITAL_PLUS_DESCRIPTION_03",
    "PRINT_DIGITAL_PLUS_DESCRIPTION_03_01",
    "PRINT_DIGITAL_PLUS_DESCRIPTION_04",
    "PRINT_DIGITAL_PLUS_DESCRIPTION_04_01",
    "PRINT_DIGITAL_PLUS_DESCRIPTION_05",
    "PRINT_DIGITAL_PLUS_DESCRIPTION_06",
    "NEW_PRINT_NALYEOM",
    "CAUTION_BACKGROUND",
    "DIGITAL_PLUS_CAUTION_BACKGROUND",
    "NEW_CAUTION_PRINT",
    "NEW_CUSTOM_DESIGN",
    "NEW_SHORT_SLEEVES_PRINT_LOCATION",
  ],
  title: "컴포트컬러즈 워싱 라운드 반팔(남여공용)"
};

export default {
  COMFORT_COLORS_1717
};
