export const GLIMMER_315_AYB = {
  attentions: ["메쉬 조직, DRY & UV CUT", "스탠다드핏, 드라이 폴로셔츠"],
  services: [
    "GLIMMER_TITLE",
    "GLIMMER_315_AYB_DESCRIPTION",
    "GLIMMER_315_AYB_GALLERY",
    "GLIMMER_315_AYB_DETAIL",
    "GLIMMER_315_AYB_COLOR",
    "GLIMMER_315_AYB_INFORMATION",
    "GLIMMER_315_AYB_SIZE_INFORMATION",
    "LAUNDRY_CARE",
    "GLIMMER_315_AYB_PRODUCT_INFORMATION",
    "PRINT_TITLE",
    "PRINT_DIGITAL",
    "PRINT_DIGITAL_COLOR",
    "PRINT_HEAT",
    "PRINT_HEAT_COLOR",
    "PRINT_NALYEOM",
    "PRINT_HOLOGRAM",
    "TRANSCRIPTION_TYPE_01",
    "PRINT_GLITTER",
    "TRANSCRIPTION_TYPE_02",
    "PRINT_NEON",
    "TRANSCRIPTION_TYPE_03",
    "CAUTION_BACKGROUND",
    "CAUTION_PRINT",
    "CUSTOM_DESIGN",
    "SHORT_SLEEVES_PRINT_LOCATION"
  ],
  title: "글리머 기능성 포켓 레이어드<br/>버튼다운 카라 반팔<br/>(남여공용)"
};

export const GLIMMER_331_ABP = {
  attentions: ["메쉬 조직, DRY & UV CUT", "스탠다드핏, 드라이 폴로셔츠"],
  services: [
    "GLIMMER_TITLE",
    "GLIMMER_331_ABP_DESCRIPTION",
    "GLIMMER_331_ABP_GALLERY",
    "GLIMMER_331_ABP_DETAIL",
    "GLIMMER_331_ABP_COLOR",
    "GLIMMER_331_ABP_INFORMATION",
    "GLIMMER_331_ABP_SIZE_INFORMATION",
    "LAUNDRY_CARE",
    "GLIMMER_331_ABP_PRODUCT_INFORMATION",
    "PRINT_TITLE",
    "PRINT_DIGITAL",
    "PRINT_DIGITAL_COLOR",
    "PRINT_HEAT",
    "PRINT_HEAT_COLOR",
    "PRINT_NALYEOM",
    "PRINT_HOLOGRAM",
    "TRANSCRIPTION_TYPE_01",
    "PRINT_GLITTER",
    "TRANSCRIPTION_TYPE_02",
    "PRINT_NEON",
    "TRANSCRIPTION_TYPE_03",
    "CAUTION_BACKGROUND",
    "CAUTION_PRINT",
    "CUSTOM_DESIGN",
    "SHORT_SLEEVES_PRINT_LOCATION"
  ],
  title: "글리머 기능성 포켓 버튼다운<br/>카라 반팔(남여공용)"
};

export const GLIMMER_300_ACT = {
  attentions: ["메쉬 조직, DRY & UV CUT", "스탠다드핏, 드라이 폴로셔츠"],
  services: [
    "GLIMMER_TITLE",
    "GLIMMER_300_ACT_DESCRIPTION",
    "GLIMMER_300_ACT_GALLERY",
    "GLIMMER_300_ACT_DETAIL_1",
    "GLIMMER_300_ACT_DETAIL_2",
    "GLIMMER_300_ACT_COLOR",
    "GLIMMER_300_ACT_INFORMATION",
    "GLIMMER_300_ACT_SIZE_INFORMATION",
    "LAUNDRY_CARE",
    "GLIMMER_300_ACT_PRODUCT_INFORMATION",
    "PRINT_TITLE",
    "PRINT_DIGITAL",
    "PRINT_DIGITAL_COLOR",
    "PRINT_HEAT",
    "PRINT_HEAT_COLOR",
    "PRINT_NALYEOM",
    "PRINT_HOLOGRAM",
    "TRANSCRIPTION_TYPE_01",
    "PRINT_GLITTER",
    "TRANSCRIPTION_TYPE_02",
    "PRINT_NEON",
    "TRANSCRIPTION_TYPE_03",
    "CAUTION_BACKGROUND",
    "CAUTION_PRINT",
    "CUSTOM_DESIGN",
    "SHORT_SLEEVES_PRINT_LOCATION"
  ],
  title: "글리머 기능성 라운드 반팔<br/>(남여공용)"
};


export const GLIMMER_300_ACT_KIDS = {
  attentions: ["메쉬 조직, DRY & UV CUT", "스탠다드핏, 드라이 폴로셔츠"],
  services: [
    "GLIMMER_TITLE",
    "GLIMMER_300_ACT_KIDS_DESCRIPTION",
    "GLIMMER_300_ACT_KIDS_DETAIL_1",
    "GLIMMER_300_ACT_KIDS_DETAIL_2",
    "GLIMMER_300_ACT_KIDS_COLOR",
    "GLIMMER_300_ACT_KIDS_INFORMATION",
    "GLIMMER_300_ACT_KIDS_SIZE_LAUNDRY_CARE",
    "GLIMMER_300_ACT_KIDS_PRODUCT_INFORMATION",
    "GLIMMER_PRINT_TITLE",
    "PRINT_DIGITAL",
    "PRINT_DIGITAL_COLOR",
    "PRINT_HEAT",
    "PRINT_HEAT_COLOR",
    "PRINT_NALYEOM",
    "PRINT_HOLOGRAM",
    "TRANSCRIPTION_TYPE_01",
    "PRINT_GLITTER",
    "TRANSCRIPTION_TYPE_02",
    "PRINT_NEON",
    "TRANSCRIPTION_TYPE_03",
    "GLIMMER_CAUTION_BACKGROUND",
    "CAUTION_PRINT",
    "GLIMMER_CUSTOM_DESIGN",
    "SHORT_SLEEVES_PRINT_LOCATION"
  ],
  title: "글리머 기능성 라운드 반팔(유아동)"
};

export default {
  GLIMMER_315_AYB,
  GLIMMER_331_ABP,
  GLIMMER_300_ACT,
  GLIMMER_300_ACT_KIDS
};
